import { useEffect, useState } from "react";
import type { Priority, Project, Recurrence, Task } from "../../data/db";

interface Props { task?: Task; projects?: Project[]; onSave: (task: Partial<Task>) => void; onClose: () => void; }

export function TaskEditor({ task, projects = [], onSave, onClose }: Props) {
  const [title,setTitle]=useState(task?.title??""); const [description,setDescription]=useState(task?.description??""); const [priority,setPriority]=useState<Priority>(task?.priority??4); const [dueDate,setDueDate]=useState(task?.dueDate??""); const [dueTime,setDueTime]=useState(task?.dueTime??""); const [duration,setDuration]=useState(task?.duration?.toString()??""); const [projectId,setProjectId]=useState(task?.projectId??""); const [tags,setTags]=useState(task?.tags.join(", ")??""); const [repeat,setRepeat]=useState<Recurrence["frequency"]|"none">(task?.recurrence?.frequency??"none"); const [interval,setInterval]=useState(task?.recurrence?.interval?.toString()??"1"); const [weekdays,setWeekdays]=useState<number[]>(task?.recurrence?.weekdays??[]);
  useEffect(()=>{setTitle(task?.title??"");setDescription(task?.description??"");setPriority(task?.priority??4);setDueDate(task?.dueDate??"");setDueTime(task?.dueTime??"");setDuration(task?.duration?.toString()??"");setProjectId(task?.projectId??"");setTags(task?.tags.join(", ")??"");setRepeat(task?.recurrence?.frequency??"none");setInterval(task?.recurrence?.interval?.toString()??"1");setWeekdays(task?.recurrence?.weekdays??[])},[task]);
  const submit=()=>{const cleanTitle=title.trim();if(!cleanTitle)return;const recurrence:Recurrence|undefined=repeat==="none"?undefined:{frequency:repeat,interval:Math.max(1,Number(interval)||1),...(repeat==="weekly"&&weekdays.length?{weekdays}: {})};onSave({title:cleanTitle,description,priority,dueDate:dueDate||undefined,dueTime:dueTime||undefined,duration:duration?Math.max(1,Number(duration)):undefined,projectId:projectId||undefined,tags:tags.split(",").map(v=>v.trim()).filter(Boolean),recurrence});};
  const toggleDay=(day:number)=>setWeekdays(v=>v.includes(day)?v.filter(x=>x!==day):[...v,day].sort());
  return <div className="modal-backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="task-editor" role="dialog" aria-modal="true" aria-label={task?"Edit task":"New task"}><div className="editor-head"><h2>{task?"Edit task":"New task"}</h2><button className="icon-btn" onClick={onClose} aria-label="Close">×</button></div><label>Title<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} onKeyDown={e=>e.key==="Escape"&&onClose()} placeholder="What needs to be done?"/></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Add notes…" rows={4}/></label><div className="editor-grid"><label>Priority<select value={priority} onChange={e=>setPriority(Number(e.target.value) as Priority)}><option value={1}>P1 — Urgent</option><option value={2}>P2 — High</option><option value={3}>P3 — Medium</option><option value={4}>P4 — Low</option></select></label><label>Project<select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">No project</option>{projects.filter(p=>!p.archived).map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Due date<input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label><label>Due time<input type="time" value={dueTime} onChange={e=>setDueTime(e.target.value)}/></label><label>Duration (minutes)<input type="number" min="1" value={duration} onChange={e=>setDuration(e.target.value)} placeholder="30"/></label><label>Tags<input value={tags} onChange={e=>setTags(e.target.value)} placeholder="work, study"/></label></div><div className="recurrence-box"><label>Repeat<select value={repeat} onChange={e=>setRepeat(e.target.value as typeof repeat)}><option value="none">Does not repeat</option><option value="daily">Every day</option><option value="weekly">Every week</option><option value="monthly">Every month</option><option value="yearly">Every year</option></select></label>{repeat!=="none"&&<label>Every <input type="number" min="1" value={interval} onChange={e=>setInterval(e.target.value)}/>{repeat==="daily"?" day(s)":repeat==="weekly"?" week(s)":repeat==="monthly"?" month(s)":" year(s)"}</label>}{repeat==="weekly"&&<div className="weekday-picker">{["S","M","T","W","T","F","S"].map((x,i)=><button type="button" className={weekdays.includes(i)?"selected":""} key={i} onClick={()=>toggleDay(i)} aria-label={`Weekday ${i}`}>{x}</button>)}</div>}</div><div className="editor-actions"><button className="secondary-btn" onClick={onClose}>Cancel</button><button className="primary-btn" onClick={submit}>{task?"Save changes":"Create task"}</button></div></div></div>;
}
