import { useEffect, useMemo, useState } from "react";
import { NavLink, Route, Routes, useLocation, useNavigate } from "react-router-dom";
import { FiCalendar, FiCheckCircle, FiChevronLeft, FiChevronRight, FiFolder, FiInbox, FiList, FiPlus, FiSearch, FiSettings, FiSun, FiTrash2 } from "react-icons/fi";
import { db, newTask, now, today, type Priority, type Task } from "../data/db";

const nav=[['/','Inbox',FiInbox],['/today','Today',FiSun],['/upcoming','Upcoming',FiList],['/calendar','Calendar',FiCalendar],['/projects','Projects',FiFolder],['/completed','Completed',FiCheckCircle],['/settings','Settings',FiSettings]] as const;

function Layout(){const [tasks,setTasks]=useState<Task[]>([]);const [query,setQuery]=useState('');const [quick,setQuick]=useState('');const [dark,setDark]=useState(false);const location=useLocation();const navg=useNavigate();
 const load=async()=>setTasks(await db.tasks.orderBy('order').reverse().toArray()); useEffect(()=>{load()},[]);
 const add=async()=>{const title=quick.trim();if(!title)return;await db.tasks.add(newTask(title));setQuick('');await load()};
 const toggle=async(t:Task)=>{await db.tasks.update(t.id,{completed:!t.completed,completedAt:!t.completed?now():undefined,status:!t.completed?'done':'todo',updatedAt:now()});await load()};
 const remove=async(t:Task)=>{await db.tasks.delete(t.id);await load()};
 const filtered=useMemo(()=>tasks.filter(t=>!query||`${t.title} ${t.description} ${t.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())),[tasks,query]);
 const title=location.pathname==='/'?'Inbox':location.pathname.slice(1).replace(/^./,x=>x.toUpperCase());
 return <div className={dark?'app dark':'app'}><aside><div className="brand"><div className="brand-icon">✓</div><div><strong>Todo Pro</strong><small>Personal productivity</small></div></div><button className="new-btn" onClick={()=>document.getElementById('quick')?.focus()}><FiPlus/> New task <kbd>N</kbd></button><nav>{nav.map(([to,label,Icon])=><NavLink key={to} to={to} end={to==='/' }><Icon/><span>{label}</span>{to==='/'&&tasks.filter(t=>!t.completed&&!t.projectId).length>0&&<b>{tasks.filter(t=>!t.completed&&!t.projectId).length}</b>}</NavLink>)}</nav><div className="sidebar-bottom"><button onClick={()=>setDark(!dark)}>{dark?'☀':'◐'} {dark?'Light':'Dark'} mode</button></div></aside><main><header><div><p className="eyebrow">MY WORKSPACE</p><h1>{title}</h1></div><div className="header-actions"><div className="search"><FiSearch/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tasks…"/></div></div></header><div className="content"><Routes><Route path="/" element={<TaskList tasks={filtered.filter(t=>!t.completed&&!t.projectId)} onToggle={toggle} onDelete={remove} quick={quick} setQuick={setQuick} add={add} title="Inbox" subtitle="Capture everything that needs your attention."/>}/><Route path="/today" element={<TaskList tasks={filtered.filter(t=>!t.completed&&t.dueDate===today())} onToggle={toggle} onDelete={remove} quick={quick} setQuick={setQuick} add={add} title="Today" subtitle="Focus on what matters today."/>}/><Route path="/upcoming" element={<TaskList tasks={filtered.filter(t=>!t.completed&&!!t.dueDate&&t.dueDate>today())} onToggle={toggle} onDelete={remove} quick={quick} setQuick={setQuick} add={add} title="Upcoming" subtitle="See what's coming next."/>}/><Route path="/completed" element={<TaskList tasks={filtered.filter(t=>t.completed)} onToggle={toggle} onDelete={remove} quick={quick} setQuick={setQuick} add={add} title="Completed" subtitle="Your finished work."/>}/><Route path="/calendar" element={<Calendar tasks={tasks} onToggle={toggle}/>} /><Route path="/projects" element={<Projects tasks={tasks}/>} /><Route path="/settings" element={<Settings dark={dark} setDark={setDark}/>} /></Routes></div></main></div>}

function TaskList({tasks,onToggle,onDelete,quick,setQuick,add,title,subtitle}:{tasks:Task[];onToggle:(t:Task)=>void;onDelete:(t:Task)=>void;quick:string;setQuick:(v:string)=>void;add:()=>void;title:string;subtitle:string}){return <section><div className="section-head"><div><h2>{title}</h2><p>{subtitle}</p></div><span className="count">{tasks.length}</span></div><div className="quick"><FiPlus/><input id="quick" value={quick} onChange={e=>setQuick(e.target.value)} onKeyDown={e=>e.key==='Enter'&&add()} placeholder="Add a task…"/><kbd>Enter</kbd></div>{tasks.length===0?<Empty title={title==='Completed'?'No completed tasks yet':title==='Today'?'You're all caught up':'Nothing here yet'} text="Add a task above to get started."/>:<div className="task-list">{tasks.map(t=><article className={'task '+(t.completed?'done':'')} key={t.id}><button className="check" onClick={()=>onToggle(t)} aria-label="Complete task">{t.completed?'✓':''}</button><div className="task-main"><div className="task-title">{t.title}</div><div className="task-meta">{t.dueDate&&<span>{t.dueDate}</span>}<span className={'priority p'+t.priority}>P{t.priority}</span>{t.tags.map(x=><span className="tag" key={x}>{x}</span>)}</div></div><button className="icon-btn" onClick={()=>onDelete(t)} aria-label="Delete task"><FiTrash2/></button></article>)}</div>}</section>}
function Empty({title,text}:{title:string;text:string}){return <div className="empty"><div className="empty-icon">✓</div><h3>{title}</h3><p>{text}</p></div>}
function Calendar({tasks,onToggle}:{tasks:Task[];onToggle:(t:Task)=>void}){const [cursor,setCursor]=useState(new Date());const y=cursor.getFullYear(),m=cursor.getMonth();const first=new Date(y,m,1).getDay();const days=new Date(y,m+1,0).getDate();const cells=Array.from({length:first+days},(_,i)=>i<first?null:i-first+1);return <section><div className="section-head"><div><h2>Calendar</h2><p>Plan and review your schedule.</p></div><div className="calendar-nav"><button onClick={()=>setCursor(new Date(y,m-1,1))}><FiChevronLeft/></button><strong>{cursor.toLocaleString('en',{month:'long',year:'numeric'})}</strong><button onClick={()=>setCursor(new Date(y,m+1,1))}><FiChevronRight/></button></div></div><div className="calendar"><div className="weekdays">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=><span key={x}>{x}</span>)}</div><div className="grid">{cells.map((d,i)=><div className={'day '+(d&&`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`===today()?'today':'')} key={i}>{d&&<><b>{d}</b>{tasks.filter(t=>t.dueDate?.slice(0,10)===`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`).slice(0,3).map(t=><button key={t.id} className={t.completed?'cal-task done':'cal-task'} onClick={()=>onToggle(t)}>{t.title}</button>)}</>}</div>)}</div></div></section>}
function Projects({tasks}:{tasks:Task[]}){const projects=[...new Set(tasks.map(t=>t.projectId).filter(Boolean))];return <section><div className="section-head"><div><h2>Projects</h2><p>Organize your work into focused areas.</p></div></div>{projects.length?<div className="project-grid">{projects.map(p=><div className="project-card" key={p}><div className="project-dot"/><strong>{p}</strong><span>{tasks.filter(t=>t.projectId===p).length} tasks</span></div>)}</div>:<Empty title="Create your first project" text="Projects will keep related tasks together."/>}</section>}
function Settings({dark,setDark}:{dark:boolean;setDark:(v:boolean)=>void}){return <section><div className="section-head"><div><h2>Settings</h2><p>Configure your personal workspace.</p></div></div><div className="settings"><div><strong>Appearance</strong><p>Choose the interface theme.</p></div><button className="setting-toggle" onClick={()=>setDark(!dark)}>{dark?'Dark':'Light'} mode</button><div><strong>Data</strong><p>Your tasks are stored locally in IndexedDB.</p></div></div></section>}

export function App(){return <Layout/>}
