import { useEffect, useMemo, useState } from "react";
import { NavLink, Route, Routes, useLocation } from "react-router-dom";
import { FiCalendar, FiCheckCircle, FiChevronLeft, FiChevronRight, FiFolder, FiInbox, FiList, FiPlus, FiSearch, FiSettings, FiSun, FiTrash2, FiBarChart2, FiColumns } from "react-icons/fi";
import { db, newTask, now, today, type Priority, type Task, type Project } from "../data/db";
import { TaskEditor } from "../components/task/TaskEditor";
import { Dashboard, Kanban, ProjectsManager } from "../components/workspace/WorkspaceViews";
import { exportBackup, importBackup } from "../data/backup";

const nav = [["/", "Inbox", FiInbox], ["/today", "Today", FiSun], ["/upcoming", "Upcoming", FiList], ["/calendar", "Calendar", FiCalendar], ["/projects", "Projects", FiFolder], ["/kanban", "Kanban", FiColumns], ["/dashboard", "Dashboard", FiBarChart2], ["/completed", "Completed", FiCheckCircle], ["/settings", "Settings", FiSettings]] as const;

export function App() {
  const [tasks,setTasks]=useState<Task[]>([]); const [projects,setProjects]=useState<Project[]>([]); const [query,setQuery]=useState(""); const [quick,setQuick]=useState(""); const [dark,setDark]=useState(()=>localStorage.getItem("todo-theme")==="dark"); const [editor,setEditor]=useState<Task|"new"|null>(null); const [undo,setUndo]=useState<(()=>Promise<void>)|null>(null);
  const location=useLocation();
  const load=async()=>{setTasks(await db.tasks.orderBy("order").reverse().toArray());setProjects(await db.projects.toArray());};
  useEffect(()=>{void load();},[]);
  useEffect(()=>{localStorage.setItem("todo-theme",dark?"dark":"light");},[dark]);
  useEffect(()=>{const h=(e:KeyboardEvent)=>{const target=e.target as HTMLElement;if(target?.tagName==="INPUT"||target?.tagName==="TEXTAREA")return;if(e.key.toLowerCase()==="n"){e.preventDefault();setEditor("new");}if(e.key==="/"||((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k")){e.preventDefault();document.getElementById("global-search")?.focus();}if(e.key==="Escape")setEditor(null)};window.addEventListener("keydown",h);return()=>window.removeEventListener("keydown",h)},[]);
  useEffect(()=>{if(!undo)return;const t=window.setTimeout(()=>setUndo(null),5000);return()=>window.clearTimeout(t)},[undo]);
  const addQuick=async()=>{const raw=quick.trim();if(!raw)return;const parsed=parseQuickAdd(raw);const task=Object.assign(newTask(parsed.title??raw),parsed);await db.tasks.add(task);setQuick("");await load();};
  const saveTask=async(patch:Partial<Task>)=>{if(editor==="new"){await db.tasks.add(Object.assign(newTask(patch.title??""),patch));}else if(editor){await db.tasks.update(editor.id,{...patch,updatedAt:now()});}setEditor(null);await load();};
  const toggle=async(task:Task)=>{const completed=!task.completed;await db.tasks.update(task.id,{completed,completedAt:completed?now():undefined,status:completed?"done":"todo",updatedAt:now()});await load();setUndo(()=>async()=>{await db.tasks.update(task.id,{completed:task.completed,completedAt:task.completedAt,status:task.status,updatedAt:now()});await load()})};
  const remove=async(task:Task)=>{await db.tasks.delete(task.id);await load();setUndo(()=>async()=>{await db.tasks.add(task);await load()})};
  const move=async(task:Task,status:Task["status"])=>{await db.tasks.update(task.id,{status,completed:status==="done",completedAt:status==="done"?now():undefined,updatedAt:now()});await load()};
  const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return tasks.filter(t=>!q||`${t.title} ${t.description} ${t.tags.join(" ")} ${t.projectId??""}`.toLowerCase().includes(q))},[tasks,query]);
  const title=location.pathname==="/"?"Inbox":location.pathname.slice(1).replace(/^./,c=>c.toUpperCase());
  return <div className={dark?"app dark":"app"}><aside><div className="brand"><div className="brand-icon">✓</div><div><strong>Todo Pro</strong><small>Personal productivity</small></div></div><button className="new-btn" onClick={()=>setEditor("new")}><FiPlus/> New task <kbd>N</kbd></button><nav>{nav.map(([to,label,Icon])=><NavLink key={to} to={to} end={to==="/"}><Icon/><span>{label}</span>{to==="/"&&tasks.filter(t=>!t.completed&&!t.projectId).length>0&&<b>{tasks.filter(t=>!t.completed&&!t.projectId).length}</b>}</NavLink>)}</nav><div className="sidebar-bottom"><button onClick={()=>setDark(v=>!v)}>{dark?"☀":"◐"} {dark?"Light":"Dark"} mode</button></div></aside>
  <main><header><div><p className="eyebrow">MY WORKSPACE</p><h1>{title}</h1></div><div className="search"><FiSearch/><input id="global-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tasks…  /" aria-label="Search tasks"/></div></header><div className="content"><Routes>
    <Route path="/" element={<TaskList tasks={filtered.filter(t=>!t.completed&&!t.projectId)} onToggle={toggle} onDelete={remove} onEdit={setEditor} quick={quick} setQuick={setQuick} add={addQuick} title="Inbox" subtitle="Capture everything that needs your attention."/>}/>
    <Route path="/today" element={<TaskList tasks={filtered.filter(t=>!t.completed&&t.dueDate===today())} onToggle={toggle} onDelete={remove} onEdit={setEditor} quick={quick} setQuick={setQuick} add={addQuick} title="Today" subtitle="Focus on what matters today."/>}/>
    <Route path="/upcoming" element={<TaskList tasks={filtered.filter(t=>!t.completed&&!!t.dueDate&&t.dueDate>today())} onToggle={toggle} onDelete={remove} onEdit={setEditor} quick={quick} setQuick={setQuick} add={addQuick} title="Upcoming" subtitle="See what is coming next."/>}/>
    <Route path="/completed" element={<TaskList tasks={filtered.filter(t=>t.completed)} onToggle={toggle} onDelete={remove} onEdit={setEditor} quick={quick} setQuick={setQuick} add={addQuick} title="Completed" subtitle="Your finished work."/>}/>
    <Route path="/calendar" element={<Calendar tasks={tasks} onToggle={toggle} onEdit={setEditor}/>}/>
    <Route path="/projects" element={<ProjectsManager tasks={tasks} projects={projects} reload={load} onEdit={setEditor}/>}/>
    <Route path="/kanban" element={<Kanban tasks={tasks} onEdit={setEditor} onMove={move}/>}/>
    <Route path="/dashboard" element={<Dashboard tasks={tasks}/>}/>
    <Route path="/settings" element={<Settings dark={dark} setDark={setDark}/>}/>
  </Routes></div></main>{editor&&<TaskEditor task={editor==="new"?undefined:editor} onSave={saveTask} onClose={()=>setEditor(null)}/>} {undo&&<div className="undo"><span>Action completed</span><button onClick={()=>{const fn=undo;setUndo(null);void fn?.()}}>Undo</button></div>}</div>;
}
function parseQuickAdd(input:string):Partial<Task>&{title?:string}{let title=input;let priority:Priority=4;const tags:string[]=[];const p=input.match(/\bp([1-4])\b/i);if(p){priority=Number(p[1]) as Priority;title=title.replace(p[0],"")}title=title.replace(/(^|\s)#([\w-]+)/g,(_,space,tag)=>{tags.push(tag);return space}).replace(/\s+/g," ").trim();const dateWord=title.match(/\b(today|tomorrow)\b/i);let dueDate:string|undefined;if(dateWord){const d=new Date();if(dateWord[1].toLowerCase()==="tomorrow")d.setDate(d.getDate()+1);dueDate=d.toISOString().slice(0,10);title=title.replace(dateWord[0],"").replace(/\s+/g," ").trim()}return{title,priority,tags,dueDate};}
function TaskList({tasks,onToggle,onDelete,onEdit,quick,setQuick,add,title,subtitle}:{tasks:Task[];onToggle:(t:Task)=>void;onDelete:(t:Task)=>void;onEdit:(t:Task)=>void;quick:string;setQuick:(v:string)=>void;add:()=>void;title:string;subtitle:string}){return <section><div className="section-head"><div><h2>{title}</h2><p>{subtitle}</p></div><span className="count">{tasks.length}</span></div><div className="quick"><FiPlus/><input id="quick" value={quick} onChange={e=>setQuick(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void add()} placeholder="Add a task… #tag p1 tomorrow"/><kbd>Enter</kbd></div>{tasks.length===0?<Empty title={title==="Completed"?"No completed tasks yet":title==="Today"?"You're all caught up":"Nothing here yet"} text="Add a task above to get started."/>:<div className="task-list">{tasks.map(t=><article className={"task "+(t.completed?"done":"")} key={t.id}><button className="check" onClick={()=>onToggle(t)} aria-label="Complete task">{t.completed?"✓":""}</button><button className="task-main task-open" onClick={()=>onEdit(t)}><div className="task-title">{t.title}</div><div className="task-meta">{t.dueDate&&<span>{t.dueDate}{t.dueTime?` ${t.dueTime}`:""}</span>}<span className={`priority p${t.priority}`}>P{t.priority}</span>{t.tags.map(x=><span className="tag" key={x}>{x}</span>)}</div></button><button className="icon-btn" onClick={()=>onDelete(t)} aria-label="Delete task"><FiTrash2/></button></article>)}</div>}</section>}
function Empty({title,text}:{title:string;text:string}){return <div className="empty"><div className="empty-icon">✓</div><h3>{title}</h3><p>{text}</p></div>}
function Calendar({tasks,onToggle,onEdit}:{tasks:Task[];onToggle:(t:Task)=>void;onEdit:(t:Task)=>void}){const[cursor,setCursor]=useState(new Date());const y=cursor.getFullYear(),m=cursor.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate();const cells=Array.from({length:first+days},(_,i)=>i<first?null:i-first+1);return <section><div className="section-head"><div><h2>Calendar</h2><p>Plan and review your schedule.</p></div><div className="calendar-nav"><button onClick={()=>setCursor(new Date(y,m-1,1))}><FiChevronLeft/></button><strong>{cursor.toLocaleString("en",{month:"long",year:"numeric"})}</strong><button onClick={()=>setCursor(new Date(y,m+1,1))}><FiChevronRight/></button></div></div><div className="calendar"><div className="weekdays">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(x=><span key={x}>{x}</span>)}</div><div className="grid">{cells.map((d,i)=>{const date=d?`${y}-${String(m+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`:"";return <div className={`day ${date===today()?"today":""}`} key={i}>{d&&<><b>{d}</b>{tasks.filter(t=>t.dueDate===date).slice(0,4).map(t=><button key={t.id} className={t.completed?"cal-task done":"cal-task"} onClick={()=>onEdit(t)} onDoubleClick={()=>onToggle(t)}>{t.title}</button>)}</>}</div>})}</div></div></section>}
function Settings({dark,setDark}:{dark:boolean;setDark:(v:boolean)=>void}){const[file,setFile]=useState<File|null>(null);const[msg,setMsg]=useState("");const restore=async()=>{if(!file)return;try{const r=await importBackup(file);setMsg(`Restored ${r.tasks} tasks, ${r.projects} projects and ${r.tags} tags.`)}catch(e){setMsg(e instanceof Error?e.message:"Import failed.")}};return <section><div className="section-head"><div><h2>Settings</h2><p>Configure your personal workspace.</p></div></div><div className="settings"><div><strong>Appearance</strong><p>Choose the interface theme.</p></div><button className="setting-toggle" onClick={()=>setDark(!dark)}>{dark?"Dark":"Light"} mode</button><div><strong>Backup</strong><p>Export every task, project and tag as JSON.</p></div><button className="setting-toggle" onClick={()=>void exportBackup()}>Export data</button><div><strong>Restore</strong><p>Import a previously exported Todo Pro backup. Existing IDs are updated safely.</p></div><input type="file" accept="application/json" onChange={e=>setFile(e.target.files?.[0]??null)}/><button className="setting-toggle" disabled={!file} onClick={()=>void restore()}>Import data</button>{msg&&<p className="muted">{msg}</p>}<div><strong>Storage</strong><p>Core data is stored locally in IndexedDB and works offline.</p></div></div></section>}
