import { useEffect, useMemo, useState } from "react";
import { NavLink, Route, Routes, useLocation } from "react-router-dom";
import { FiCalendar, FiCheckCircle, FiChevronLeft, FiChevronRight, FiFolder, FiInbox, FiList, FiPlus, FiSearch, FiSettings, FiSun, FiTrash2 } from "react-icons/fi";
import { db, newTask, now, today, type Priority, type Task } from "../data/db";
import { TaskEditor } from "../components/task/TaskEditor";

const nav = [["/", "Inbox", FiInbox], ["/today", "Today", FiSun], ["/upcoming", "Upcoming", FiList], ["/calendar", "Calendar", FiCalendar], ["/projects", "Projects", FiFolder], ["/completed", "Completed", FiCheckCircle], ["/settings", "Settings", FiSettings]] as const;

export function App() {
  const [tasks, setTasks] = useState<Task[]>([]); const [query, setQuery] = useState(""); const [quick, setQuick] = useState(""); const [dark, setDark] = useState(false); const [editor, setEditor] = useState<Task | "new" | null>(null); const [undo, setUndo] = useState<(() => Promise<void>) | null>(null);
  const location = useLocation();
  const load = async () => setTasks(await db.tasks.orderBy("order").reverse().toArray());
  useEffect(() => { void load(); }, []);
  useEffect(() => { const handler = (e: KeyboardEvent) => { if ((e.target as HTMLElement)?.tagName === "INPUT" || (e.target as HTMLElement)?.tagName === "TEXTAREA") return; if (e.key.toLowerCase() === "n") { e.preventDefault(); setEditor("new"); } if (e.key === "/") { e.preventDefault(); document.getElementById("global-search")?.focus(); } if (e.key === "Escape") setEditor(null); }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, []);
  useEffect(() => { if (!undo) return; const timer = window.setTimeout(() => setUndo(null), 5000); return () => window.clearTimeout(timer); }, [undo]);
  const addQuick = async () => { const title = quick.trim(); if (!title) return; const task = newTask(title); const parsed = parseQuickAdd(title); Object.assign(task, parsed); task.title = parsed.title ?? title; await db.tasks.add(task); setQuick(""); await load(); };
  const saveTask = async (patch: Partial<Task>) => { if (editor === "new") { const task = Object.assign(newTask(patch.title ?? ""), patch); await db.tasks.add(task); } else if (editor) { await db.tasks.update(editor.id, { ...patch, updatedAt: now() }); } setEditor(null); await load(); };
  const toggle = async (task: Task) => { const completed = !task.completed; await db.tasks.update(task.id, { completed, completedAt: completed ? now() : undefined, status: completed ? "done" : "todo", updatedAt: now() }); await load(); setUndo(() => async () => { await db.tasks.update(task.id, { completed: task.completed, completedAt: task.completedAt, status: task.status, updatedAt: now() }); await load(); }); };
  const remove = async (task: Task) => { await db.tasks.delete(task.id); await load(); setUndo(() => async () => { await db.tasks.add(task); await load(); }); };
  const filtered = useMemo(() => { const q = query.trim().toLowerCase(); return tasks.filter(t => !q || `${t.title} ${t.description} ${t.tags.join(" ")}`.toLowerCase().includes(q)); }, [tasks, query]);
  const title = location.pathname === "/" ? "Inbox" : location.pathname.slice(1).replace(/^./, c => c.toUpperCase());
  return <div className={dark ? "app dark" : "app"}>
    <aside><div className="brand"><div className="brand-icon">✓</div><div><strong>Todo Pro</strong><small>Personal productivity</small></div></div><button className="new-btn" onClick={() => setEditor("new")}><FiPlus/> New task <kbd>N</kbd></button><nav>{nav.map(([to, label, Icon]) => <NavLink key={to} to={to} end={to === "/"}><Icon/><span>{label}</span>{to === "/" && tasks.filter(t => !t.completed && !t.projectId).length > 0 && <b>{tasks.filter(t => !t.completed && !t.projectId).length}</b>}</NavLink>)}</nav><div className="sidebar-bottom"><button onClick={() => setDark(v => !v)}>{dark ? "☀" : "◐"} {dark ? "Light" : "Dark"} mode</button></div></aside>
    <main><header><div><p className="eyebrow">MY WORKSPACE</p><h1>{title}</h1></div><div className="search"><FiSearch/><input id="global-search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search tasks…  /" aria-label="Search tasks"/></div></header><div className="content"><Routes>
      <Route path="/" element={<TaskList tasks={filtered.filter(t => !t.completed && !t.projectId)} onToggle={toggle} onDelete={remove} onEdit={setEditor} quick={quick} setQuick={setQuick} add={addQuick} title="Inbox" subtitle="Capture everything that needs your attention."/>}/>
      <Route path="/today" element={<TaskList tasks={filtered.filter(t => !t.completed && t.dueDate === today())} onToggle={toggle} onDelete={remove} onEdit={setEditor} quick={quick} setQuick={setQuick} add={addQuick} title="Today" subtitle="Focus on what matters today."/>}/>
      <Route path="/upcoming" element={<TaskList tasks={filtered.filter(t => !t.completed && !!t.dueDate && t.dueDate > today())} onToggle={toggle} onDelete={remove} onEdit={setEditor} quick={quick} setQuick={setQuick} add={addQuick} title="Upcoming" subtitle="See what is coming next."/>}/>
      <Route path="/completed" element={<TaskList tasks={filtered.filter(t => t.completed)} onToggle={toggle} onDelete={remove} onEdit={setEditor} quick={quick} setQuick={setQuick} add={addQuick} title="Completed" subtitle="Your finished work."/>}/>
      <Route path="/calendar" element={<Calendar tasks={tasks} onToggle={toggle} onEdit={setEditor}/>} />
      <Route path="/projects" element={<Projects tasks={tasks} onEdit={setEditor}/>} />
      <Route path="/settings" element={<Settings dark={dark} setDark={setDark}/>} />
    </Routes></div></main>
    {editor && <TaskEditor task={editor === "new" ? undefined : editor} onSave={saveTask} onClose={() => setEditor(null)}/>} {undo && <div className="undo"><span>Action completed</span><button onClick={() => { const fn = undo; setUndo(null); void fn?.(); }}>Undo</button></div>}
  </div>;
}

function parseQuickAdd(input: string): Partial<Task> & { title?: string } { let title = input; let priority: Priority = 4; const tags: string[] = []; const p = input.match(/\bp([1-4])\b/i); if (p) { priority = Number(p[1]) as Priority; title = title.replace(p[0], ""); } title = title.replace(/(^|\s)#([\w-]+)/g, (_, space, tag) => { tags.push(tag); return space; }).replace(/\s+/g, " ").trim(); return { title, priority, tags }; }

function TaskList({ tasks, onToggle, onDelete, onEdit, quick, setQuick, add, title, subtitle }: { tasks: Task[]; onToggle: (t: Task) => void; onDelete: (t: Task) => void; onEdit: (t: Task) => void; quick: string; setQuick: (v: string) => void; add: () => void; title: string; subtitle: string }) { return <section><div className="section-head"><div><h2>{title}</h2><p>{subtitle}</p></div><span className="count">{tasks.length}</span></div><div className="quick"><FiPlus/><input id="quick" value={quick} onChange={e => setQuick(e.target.value)} onKeyDown={e => e.key === "Enter" && void add()} placeholder="Add a task… #tag p1"/><kbd>Enter</kbd></div>{tasks.length === 0 ? <Empty title={title === "Completed" ? "No completed tasks yet" : title === "Today" ? "You're all caught up" : "Nothing here yet"} text="Add a task above to get started."/> : <div className="task-list">{tasks.map(t => <article className={"task " + (t.completed ? "done" : "")} key={t.id}><button className="check" onClick={() => onToggle(t)} aria-label="Complete task">{t.completed ? "✓" : ""}</button><button className="task-main task-open" onClick={() => onEdit(t)}><div className="task-title">{t.title}</div><div className="task-meta">{t.dueDate && <span>{t.dueDate}{t.dueTime ? ` ${t.dueTime}` : ""}</span>}<span className={`priority p${t.priority}`}>P{t.priority}</span>{t.tags.map(x => <span className="tag" key={x}>{x}</span>)}</div></button><button className="icon-btn" onClick={() => onDelete(t)} aria-label="Delete task"><FiTrash2/></button></article>)}</div>}</section> }
function Empty({ title, text }: { title: string; text: string }) { return <div className="empty"><div className="empty-icon">✓</div><h3>{title}</h3><p>{text}</p></div>; }
function Calendar({ tasks, onToggle, onEdit }: { tasks: Task[]; onToggle: (t: Task) => void; onEdit: (t: Task) => void }) { const [cursor, setCursor] = useState(new Date()); const y = cursor.getFullYear(), m = cursor.getMonth(); const first = new Date(y, m, 1).getDay(); const days = new Date(y, m + 1, 0).getDate(); const cells = Array.from({ length: first + days }, (_, i) => i < first ? null : i - first + 1); return <section><div className="section-head"><div><h2>Calendar</h2><p>Plan and review your schedule.</p></div><div className="calendar-nav"><button onClick={() => setCursor(new Date(y, m - 1, 1))}><FiChevronLeft/></button><strong>{cursor.toLocaleString("en", { month: "long", year: "numeric" })}</strong><button onClick={() => setCursor(new Date(y, m + 1, 1))}><FiChevronRight/></button></div></div><div className="calendar"><div className="weekdays">{["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map(x => <span key={x}>{x}</span>)}</div><div className="grid">{cells.map((d, i) => { const date = d ? `${y}-${String(m + 1).padStart(2, "0")}-${String(d).padStart(2, "0")}` : ""; return <div className={`day ${date === today() ? "today" : ""}`} key={i}>{d && <><b>{d}</b>{tasks.filter(t => t.dueDate === date).slice(0, 4).map(t => <button key={t.id} className={t.completed ? "cal-task done" : "cal-task"} onClick={() => onEdit(t)} onDoubleClick={() => onToggle(t)}>{t.title}</button>)}</>}</div>; })}</div></div></section>; }
function Projects({ tasks, onEdit }: { tasks: Task[]; onEdit: (t: Task) => void }) { const projects = [...new Set(tasks.map(t => t.projectId).filter((p): p is string => Boolean(p)))]; return <section><div className="section-head"><div><h2>Projects</h2><p>Organize related work into focused areas.</p></div></div>{projects.length ? <div className="project-grid">{projects.map(p => <div className="project-card" key={p}><div className="project-dot"/><strong>{p}</strong><span>{tasks.filter(t => t.projectId === p).length} tasks</span>{tasks.filter(t => t.projectId === p).slice(0, 3).map(t => <button className="project-task" key={t.id} onClick={() => onEdit(t)}>{t.title}</button>)}</div>)}</div> : <Empty title="No projects yet" text="Use the task editor to assign tasks to projects as the project manager is added."/>}</section>; }
function Settings({ dark, setDark }: { dark: boolean; setDark: (v: boolean) => void }) { return <section><div className="section-head"><div><h2>Settings</h2><p>Configure your personal workspace.</p></div></div><div className="settings"><div><strong>Appearance</strong><p>Choose the interface theme.</p></div><button className="setting-toggle" onClick={() => setDark(!dark)}>{dark ? "Dark" : "Light"} mode</button><div><strong>Storage</strong><p>All core data is stored locally in IndexedDB and survives refreshes and offline usage.</p></div></div></section>; }
